# Generated by Django 5.2 on 2025-06-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_fooditem_common_serving_size_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritiongoal',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
