# Generated by Django 5.2 on 2025-06-21 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_nutritiongoal_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumeditem',
            name='food_item',
        ),
        migrations.AddField(
            model_name='consumeditem',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.fooditem'),
        ),
    ]
