# Generated by Django 5.2 on 2025-06-21 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_consumeditem_food_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumeditem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='consumeditem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.fooditem'),
        ),
    ]
